apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: job-portal-backend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: splendid-petal-471416-f6:me-west1:job-portal
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      containers:
        - image: me-west1-docker.pkg.dev/splendid-petal-471416-f6/job-portal-api/job-portal-api:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: NODE_ENV
              value: production
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: splendid-petal-471416-f6
            - name: GOOGLE_CLOUD_BUCKET_NAME
              value: job-portal-media
            - name: DATABASE_URL
              value: "postgresql://postgres:Qw123456789%3D%3D@localhost/job-portal?host=/cloudsql/splendid-petal-471416-f6:me-west1:job-portal"
            - name: JWT_SECRET
              value: "R+HGvdW+YewpDjXg6UXtrIPp3w6p+5meH9+C92BNFqsSDXCo2OnIDOsQS3ZEB0iJ"
  traffic:
    - percent: 100
      latestRevision: true
