name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  SERVICE_NAME: job-portal-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:${{ github.sha }} .
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:${{ github.sha }} \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:latest

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:${{ github.sha }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:latest

      - name: Deploy to Cloud Run
        env:
          CLOUD_SQL_CONNECTION: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        run: |
          # Build the base deploy command
          DEPLOY_CMD="gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/job-portal-api/job-portal-api:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 2Gi \
            --cpu 2 \
            --timeout 600 \
            --max-instances 10 \
            --min-instances 0 \
            --port 8080 \
            --set-env-vars PORT=8080,NODE_ENV=production \
            --set-env-vars DATABASE_URL=\"${{ secrets.DATABASE_URL }}\" \
            --set-env-vars JWT_SECRET=\"${{ secrets.JWT_SECRET }}\""

          # Add Cloud SQL connection if provided
          if [ ! -z "$CLOUD_SQL_CONNECTION" ]; then
            DEPLOY_CMD="$DEPLOY_CMD --add-cloudsql-instances $CLOUD_SQL_CONNECTION"
          fi

          # Execute deployment
          eval $DEPLOY_CMD

      - name: Show service URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --format 'value(status.url)'
